export const user = [
    {
        name: 'Seth Williams',
        profile: 'Managing director',
        img: 'src/assets/icons/icon-more.svg',
        add_img: 'src/assets/icons/icon-add.svg',
        product: 'Retail',
        // country: 'Brazil',
        // country_flag: 'src/assets/icons/flag-brazil.png',
        children: [
            {
                name: 'Ramon Harris',
                profile: 'Regional director',
                img: 'src/assets/icons/icon-more.svg',
                add_img: 'src/assets/icons/icon-add.svg',
                product: 'Retail',
                country: 'Brazil',
                country_flag: 'src/assets/icons/flag-brazil.png',
                children: [
                    {
                        name: 'Fanet Parks',
                        profile: 'CEO',
                        img: 'src/assets/icons/icon-more.svg',
                        add_img: 'src/assets/icons/icon-add.svg',
                        product: 'Retail',
                        children: [],
                    },
                    {
                        name: 'Isabelle Kaif',
                        profile: 'CEO',
                        img: 'src/assets/icons/icon-more.svg',
                        add_img: 'src/assets/icons/icon-add.svg',
                        product: 'Retail',
                        children: [],
                    },
                ],
            },
            {
                name: 'Dan Morgan',
                profile: 'Regional director',
                img: 'src/assets/icons/icon-more.svg',
                add_img: 'src/assets/icons/icon-add.svg',
                product: 'Retail',
                country: 'USA',
                country_flag: 'src/assets/icons/flag-usa.png',
                children: [
                    {
                        name: 'Ivan Toney',
                        profile: 'CEO',
                        img: 'src/assets/icons/icon-more.svg',
                        add_img: 'src/assets/icons/icon-add.svg',
                        product: 'Retail',
                        children: [
                            {
                                name: 'Brian Walker',
                                profile: 'Chief Administrator',
                                img: 'src/assets/icons/icon-more.svg',
                                add_img: 'src/assets/icons/icon-add.svg',
                                product: 'Retail',
                                children: [],
                            },

                            {
                                name: 'Vera Martinez',
                                profile: 'Chief Administrator',
                                img: 'src/assets/icons/icon-more.svg',
                                add_img: 'src/assets/icons/icon-add.svg',
                                product: 'Retail',
                                children: [],
                            },
                        ],
                    },

                    {
                        name: 'Sabrina Francis',
                        profile: 'CEO',
                        img: 'src/assets/icons/icon-more.svg',
                        add_img: 'src/assets/icons/icon-add.svg',
                        product: 'Retail',
                        children: [],
                    },
                ],
            },
            {
                name: 'Stella Nelson',
                profile: 'Regional director',
                img: 'src/assets/icons/icon-more.svg',
                add_img: 'src/assets/icons/icon-add.svg',
                product: 'Retail',
                country: 'Italy',
                country_flag: 'src/assets/icons/flag-italy.png',
                children: [
                    {
                        name: 'Miles Clark',
                        profile: 'Chief Administrator',
                        img: 'src/assets/icons/icon-more.svg',
                        add_img: 'src/assets/icons/icon-add.svg',
                        product: 'Retail',
                        children: [],
                    },
                    {
                        name: 'Angela',
                        profile: 'Chief Administrator',
                        img: 'src/assets/icons/icon-more.svg',
                        add_img: 'src/assets/icons/icon-add.svg',
                        product: 'Retail',
                        children: [],
                    },
                ],
            },
        ],
    },
]
// {
//     name: 'Dave Cooper',
//     profile: 'Regional director',
//     img: 'src/assets/icons/icon-more.svg',
//     add_img: 'src/assets/icons/icon-add.svg',
//     product: 'Retail',
//     country: 'USA',
//     country_flag: 'src/assets/icons/flag-usa.png',
// },
// {
//     name: 'Ramon Harris',
//     profile: 'Regional director',
//     img: 'src/assets/icons/icon-more.svg',
//     add_img: 'src/assets/icons/icon-add.svg',
//     product: 'Retail',
//     country: 'Italy',
//     country_flag: 'src/assets/icons/flag-italy.png',
// },
// {
//     name: 'Dan Morgan',
//     profile: 'Regional director',
//     img: 'src/assets/icons/icon-more.svg',
//     add_img: 'src/assets/icons/icon-add.svg',
//     product: 'Retail',
//     country: 'Brazil',
//     country_flag: 'src/assets/icons/flag-brazil.png',
// },
// {
//     name: 'Fanet Parks',
//     profile: 'CEO',
//     img: 'src/assets/icons/icon-more.svg',
//     add_img: 'src/assets/icons/icon-add.svg',
//     product: 'Retail',
//     country: 'USA',
//     country_flag: 'src/assets/icons/flag-usa.png',
// },
// {
//     name: 'Isabelle Kaif',
//     profile: 'CEO',
//     img: 'src/assets/icons/icon-more.svg',
//     add_img: 'src/assets/icons/icon-add.svg',
//     product: 'Retail',
//     country: 'Italy',
//     country_flag: 'src/assets/icons/flag-italy.png',
// },
// {
//     name: 'Dan Morgan',
//     profile: 'Marta Colvin Andrade',
//     img: 'src/assets/icons/icon-more.svg',
//     add_img: 'src/assets/icons/icon-add.svg',
//     product: 'Retail',
//     country: 'Brazil',
//     country_flag: 'src/assets/icons/flag-brazil.png',
// },
// {
//     name: 'Ivan Toney',
//     profile: 'CEO',
//     img: 'src/assets/icons/icon-more.svg',
//     add_img: 'src/assets/icons/icon-add.svg',
//     product: 'Retail',
//     country: 'USA',
//     country_flag: 'src/assets/icons/flag-usa.png',
// },
// {
//     name: 'Sabrina Francis',
//     profile: 'CEO',
//     img: 'src/assets/icons/icon-more.svg',
//     add_img: 'src/assets/icons/icon-add.svg',
//     product: 'Retail',
//     country: 'Italy',
//     country_flag: 'src/assets/icons/flag-italy.png',
// },
// {
//     name: 'Miles Clark',
//     profile: 'Chief Administrator',
//     img: 'src/assets/icons/icon-more.svg',
//     add_img: 'src/assets/icons/icon-add.svg',
//     product: 'Retail',
//     country: 'Brazil',
//     country_flag: 'src/assets/icons/flag-brazil.png',
// },
// {
//     name: 'Angela',
//     profile: 'Chief Administrator',
//     img: 'src/assets/icons/icon-more.svg',
//     add_img: 'src/assets/icons/icon-add.svg',
//     product: 'Retail',
//     country: 'USA',
//     country_flag: 'src/assets/icons/flag-usa.png',
// },
// {
//     name: 'Brian Walker',
//     profile: 'Chief Administrator',
//     img: 'src/assets/icons/icon-more.svg',
//     add_img: 'src/assets/icons/icon-add.svg',
//     product: 'Retail',
//     country: 'Italy',
//     country_flag: 'src/assets/icons/flag-italy.png',
// },
// {
//     name: 'Vera Martinez',
//     profile: 'Chief Administrator',
//     img: 'src/assets/icons/icon-more.svg',
//     add_img: 'src/assets/icons/icon-add.svg',
//     product: 'Retail',
//     country: 'Brazil',
//     country_flag: 'src/assets/icons/flag-brazil.png',
// },

// export const user1 = [
//     {
//         name: 'Seth Williams',
//         profile: 'Managing director',
//         img: 'src/assets/icons/icon-more.svg',
//         add_img: 'src/assets/icons/icon-add.svg',
//         country: 'Brazil',
//         country_flag: 'src/assets/icons/flag-brazil.png',
//     },
//     {
//         name: 'Dave Cooper',
//         profile: 'Regional director',
//         img: 'src/assets/icons/icon-more.svg',
//         add_img: 'src/assets/icons/icon-add.svg',
//         country: 'USA',
//         country_flag: 'src/assets/icons/flag-usa.png',
//     },
// ]
