export const USERS = [
    {
        name: 'Seth Williams',
        profile: 'Managing director',
        profile_img: 'src/assets/images/user1.svg',
        img: 'src/assets/icons/icon-more.svg',
        add_img: 'src/assets/icons/icon-add.svg',
        product: 'Retail',
        select: false,
        children: [
            {
                name: 'Ramon Harris',
                profile: 'Regional director',
                profile_img: 'src/assets/images/user2.svg',
                img: 'src/assets/icons/icon-more.svg',
                add_img: 'src/assets/icons/icon-add.svg',
                product: 'Retail',
                country: 'Brazil',
                country_flag: 'src/assets/icons/flag-brazil.png',
                select: false,
                children: [
                    {
                        name: 'Janet Parks',
                        profile: 'CEO',
                        profile_img: 'src/assets/images/user5.svg',
                        img: 'src/assets/icons/icon-more.svg',
                        add_img: 'src/assets/icons/icon-add.svg',
                        product: 'Retail',
                        select: true,
                        children: [],
                    },
                    {
                        name: 'Isabelle Kaif',
                        profile: 'CEO',
                        profile_img: 'src/assets/images/user6.svg',
                        img: 'src/assets/icons/icon-more.svg',
                        add_img: 'src/assets/icons/icon-add.svg',
                        product: 'Retail',
                        select: false,
                        children: [],
                    },
                ],
            },
            {
                name: 'Dan Morgan',
                profile: 'Regional director',
                profile_img: 'src/assets/images/user3.svg',
                img: 'src/assets/icons/icon-more.svg',
                add_img: 'src/assets/icons/icon-add.svg',
                product: 'Retail',
                country: 'USA',
                country_flag: 'src/assets/icons/flag-usa.png',
                select: false,
                children: [
                    {
                        name: 'Ivan Toney',
                        profile: 'CEO',
                        profile_img: 'src/assets/images/user7.svg',
                        img: 'src/assets/icons/icon-more.svg',
                        add_img: 'src/assets/icons/icon-add.svg',
                        product: 'Retail',
                        select: true,
                        children: [
                            {
                                name: 'Brian Walker',
                                profile: 'Chief Administrator',
                                profile_img: 'src/assets/images/user9.svg',
                                img: 'src/assets/icons/icon-more.svg',
                                add_img: 'src/assets/icons/icon-add.svg',
                                product: 'Retail',
                                select: false,
                                children: [],
                            },

                            {
                                name: 'Vera Martinez',
                                profile: 'Chief Administrator',
                                profile_img: 'src/assets/images/user12.svg',
                                img: 'src/assets/icons/icon-more.svg',
                                add_img: 'src/assets/icons/icon-add.svg',
                                product: 'Retail',
                                select: false,
                                children: [],
                            },
                        ],
                    },

                    {
                        name: 'Sabrina Francis',
                        profile: 'CEO',
                        profile_img: 'src/assets/images/user8.svg',
                        img: 'src/assets/icons/icon-more.svg',
                        add_img: 'src/assets/icons/icon-add.svg',
                        product: 'Retail',
                        select: false,
                        children: [],
                    },
                ],
            },
            {
                name: 'Stella Nelson',
                profile: 'Regional director',
                profile_img: 'src/assets/images/user4.svg',
                img: 'src/assets/icons/icon-more.svg',
                add_img: 'src/assets/icons/icon-add.svg',
                product: 'Retail',
                country: 'Italy',
                country_flag: 'src/assets/icons/flag-italy.png',
                select: false,
                children: [
                    {
                        name: 'Miles Clark',
                        profile: 'Chief Administrator',
                        profile_img: 'src/assets/images/user9.svg',
                        img: 'src/assets/icons/icon-more.svg',
                        add_img: 'src/assets/icons/icon-add.svg',
                        product: 'Retail',
                        select: true,
                        children: [],
                    },
                    {
                        name: 'Angela Howard',
                        profile: 'Chief Administrator',
                        profile_img: 'src/assets/images/user10.svg',
                        img: 'src/assets/icons/icon-more.svg',
                        add_img: 'src/assets/icons/icon-add.svg',
                        product: 'Retail',
                        select: true,
                        children: [],
                    },
                ],
            },
        ],
    },
]
